---
# This file is used by the automations editor
# in the Home Assistant frontend.
#
# I personally do not use it, mainly because I like doing this in YAML.
# However, from time to time, it is helpful to click a bit and see
# what the frontend makes of it.
#
# This file must exist for the frontend Automation editor to work.
# Hence, it is here, empty.
#
# If you are looking for my automations: See automations folder.

- id: update_morning_commute_sensor
  alias: Commute - Update morning commute sensor
  initial_state: 'on'
  trigger:
  - platform: time_pattern
    minutes: /2
  condition:
  - condition: time
    after: 06:00:00
    before: 07:00:00
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: homeassistant.update_entity
    entity_id: sensor.phone_to_work

