homeassistant:
  name: Selby
  latitude: !secret selby_latitude
  longitude: !secret selby_longitude
  elevation: !secret selby_elevation
  unit_system: metric
  time_zone: Australia/Melbourne
  packages: !include_dir_named include
  external_url: https://hassio.selby.michaelgreenhill.net
  
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.178.0/24
        - 127.0.0.1
        - ::1
      trusted_users:
        192.168.178.109: !secret trusted_user_hash # michael
      allow_bypass_login: true
    - type: homeassistant

  # Customization file
  #customize: !include customize.yaml


# https://community.home-assistant.io/t/wunderground-data-uploader/330332
# Required for wunderground uploader
shell_command:
  curl_get: 'curl -X GET {{ url }}'


# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url: 
    - /hacsfiles/lovelace-card-mod/card-mod.js

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
#updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Text to speech
#tts:
#  - platform: google

tplink:
  discovery: true
#  strip:
#    - host: 192.168.178.101
  switch:
    - host: 192.168.178.102
    - host: 192.168.178.104
    - host: 192.168.178.153


stream:
  ll_hls: true

media_player:

speedtestdotnet:
  scan_interval: "06:00:00"

zone:
  - name: Money3
    icon: mdi:briefcase
    latitude: !secret work_latitude
    longitude: !secret work_longitude
  - name: Selby
    icon: mdi:house
    latitude: !secret selby_latitude
    longitude: !secret selby_longitude
    radius: 100



browser_mod: