homeassistant:
  name: Selby
  latitude: !secret selby_latitude
  longitude: !secret selby_longitude
  elevation: !secret selby_elevation
  unit_system: metric
  time_zone: Australia/Melbourne
  packages: !include_dir_named include
  external_url: https://hassio.selby.michaelgreenhill.net
  
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.178.0/24
        - 127.0.0.1
        - ::1
      trusted_users:
        192.168.178.109: !secret trusted_user_hash # michael
      allow_bypass_login: true
    - type: homeassistant

  # Customization file
  #customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# https://www.home-assistant.io/integrations/my/
# Required for importing blueprints
my: 

# https://community.home-assistant.io/t/wunderground-data-uploader/330332
# Required for wunderground uploader
shell_command:
  curl_get: 'curl -X GET {{ url }}'

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/bar-card/bar-card.js
      type: module
    - url: /hacsfiles/kiosk-mode/kiosk-mode.js?v=1.6.5
      type: module
    - url: /hacsfiles/light-popup-card/light-popup-card.js
      type: module
    - url: /hacsfiles/lovelace-hui-element/hui-element.js
      type: module
    - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/swipe-card/swipe-card.js
      type: module
    - url: /hacsfiles/bom-weather-card/bom-weather-card.js
      type: module
    - url: /hacsfiles/weather-card/weather-card.js
      type: module
    - url: /hacsfiles/spotify-card/spotify-card.js
      type: module
    - url: 'https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700&display=swap'
      type: css
    - url: /dwains_dashboard/cards/dwains-wrapper-card/dwains-wrapper-card.js?v=2.0.5
      type: module
    - url: /dwains_dashboard/cards/dwains-weather-card/dwains-weather-card.js?v=2.0.5
      type: module
    - url: /dwains_dashboard/cards/dwains-notification-card/dwains-notification-card.js?v=2.0.5
      type: module
    - url: /dwains_dashboard/cards/dwains-header-card/dwains-header-card.js?v=2.0.5
      type: module
    - url: /dwains_dashboard/cards/dwains-auto-entities-card/dwains-auto-entities-card.js?v=2.0.5
      type: module
    - url: /dwains_dashboard/js/dwains-dashboard.js?v=2.0.5
      type: module
    - url: /dwains_dashboard/cards/dwains-collapse-card/dwains-collapse-card.js?v=2.0.5
      type: module
    - url: /dwains_dashboard/cards/dwains-heading-card/dwains-heading-card.js?v=2.0.5
      type: module
    - url: /dwains_dashboard/cards/dwains-hash-switch-card/dwains-hash-switch-card.js?v=2.0.5
      type: module
    - url: /dwains_dashboard/cards/button-card/button-card.js?v=2.0.5
      type: module
    - url: /dwains_dashboard/cards/dwains-cover-card/dwains-cover-card.js?v=2.0.5
      type: module
    #- url: /dwains_dashboard/cards/light-entity-card/light-entity-card.js?v=2.0.5
    #  type: module
    - url: /dwains_dashboard/cards/dwains-flexbox-card/dwains-flexbox-card.js?v=2.0.5
      type: module
    - url: https://fonts.googleapis.com/css?family=Comfortaa&display=swap
      type: css
    - url: /hacsfiles/kb-better-graph-colors/kb-better-graph-colors.js
      type: module
    - url: /local/custom-gh.css
      type: css
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/light-popup-card/light-popup-card.js
      type: module
    - url: /hacsfiles/compass-card/compass-card.js
      type: module

  dashboards:
    lovelace-generated: # Needs to contain a hyphen (-)
      mode: yaml
      filename: notexist.yaml
      title: Generated
      icon: mdi:tools
      show_in_sidebar: true
      require_admin: true
    lovelace-home:
      mode: yaml
      filename: ui-home2022.yaml
      title: Home
      icon: mdi:home
      show_in_sidebar: true
      require_admin: true
    

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url: 
    - /hacsfiles/lovelace-card-mod/card-mod.js

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.178.37
    - 192.168.178.33
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
#updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
#tts:
#  - platform: google

# Cloud
cloud:

tplink:
  discovery: true
#  strip:
#    - host: 192.168.178.101
  switch:
    - host: 192.168.178.102
    - host: 192.168.178.104
    - host: 192.168.178.153

mobile_app:

climate:
  - platform: sensibo
    api_key: !secret sensibo_api_key

stream:
  ll_hls: true

media_player:

speedtestdotnet:
  scan_interval: "06:00:00"

zone:
  - name: Money3
    icon: mdi:briefcase
    latitude: !secret work_latitude
    longitude: !secret work_longitude
  - name: Selby
    icon: mdi:house
    latitude: !secret selby_latitude
    longitude: !secret selby_longitude
    radius: 100

prometheus:

recorder:
  auto_purge: true
  purge_keep_days: 14
  commit_interval: 5
  db_url: !secret mariadb_url
  exclude:
    domains:
      - automation
      - updater
      - media_player
      - device_tracker
    entity_globs:
      - sensor.weather_*
    entities:
      - sun.sun # Don't record sun data
      - sensor.last_boot # Comes from 'systemmonitor' sensor platform
      - sensor.date
    event_types:
      - call_service # Don't record service calls

logbook:
  exclude:
    domains:
      - media_player
      - device_tracker
      - updater
    entities:
      - sensor.date

system_health:

browser_mod:

group: !include groups.yaml
automation: !include automations.yaml
#script: !include scripts.yaml
light: !include lights.yaml
