---
#
# https://community.home-assistant.io/t/cannot-get-tuya-integration-to-work/226356/41
#

id: '8b5a12e6-6c93-4039-9430-64d812ac4f8f'
alias: Set iBBQ Timer
description: ''
trigger:
- platform: state
  entity_id: input_boolean.ibbqtimeswitch
  to: 'on'
condition: []
action:
- service: timer.start
  data:
    duration: '{{ (states.input_number.ibbq_timer_setting.state | int) * 60 }}'
  target:
    entity_id: timer.ibbq_timer
mode: single