---

id: '1649746845705'
alias: Kitchen - Turn off dim lights at night after motion ends
description: ''
trigger:
- type: no_motion
  platform: device
  device_id: 41622ebcffbf84a3fb68b12e38e010cf
  entity_id: binary_sensor.lumi_lumi_sensor_motion_7b9b4305_ias_zone
  domain: binary_sensor
  for:
    hours: 0
    minutes: 0
    seconds: 5
condition:
- condition: device
  type: is_on
  device_id: a8b64e55ded335ad42689a13a8a10a6b
  entity_id: light.kitchen_2
  domain: light
- condition: time
  before: 05:00:00
  after: '23:00:00'
  weekday:
  - mon
  - tue
  - wed
  - thu
  - fri
  - sat
  - sun
- condition: device
  type: is_off
  device_id: 21f7fe7a58392131a46357cf7e6007ba
  entity_id: light.living_room
  domain: light
action:
- type: turn_off
  device_id: a8b64e55ded335ad42689a13a8a10a6b
  entity_id: light.kitchen_2
  domain: light
mode: single