---

id: '1649745770599'
alias: Kitchen - Turn on dim lights at night with motion
description: ''
trigger:
- type: motion
  platform: device
  device_id: 41622ebcffbf84a3fb68b12e38e010cf
  entity_id: binary_sensor.lumi_lumi_sensor_motion_7b9b4305_ias_zone
  domain: binary_sensor
condition:
  - condition: device
    type: is_off
    device_id: a8b64e55ded335ad42689a13a8a10a6b
    entity_id: light.kitchen_2
    domain: light
  - condition: state
    entity_id: schedule.nightlight_hours
    state: "on"
  - condition: device
    type: is_off
    device_id: 21f7fe7a58392131a46357cf7e6007ba
    entity_id: light.living_room
    domain: light
action:
- service: hue.hue_activate_scene
  data:
    scene_name: Nightlight
    group_name: Kitchen
mode: single