---

id: '1650000125739'
alias: Kitchen - Turn on dim lights at night with motion 5am
description: 'Turns on the kitchen lights with low brightness if motion is detected after 5 a.m. Useful for early morning starts.'
trigger:
- type: motion
  platform: device
  device_id: 41622ebcffbf84a3fb68b12e38e010cf
  entity_id: binary_sensor.lumi_lumi_sensor_motion_7b9b4305_ias_zone
  domain: binary_sensor
condition:
- condition: device
  type: is_off
  device_id: a8b64e55ded335ad42689a13a8a10a6b
  entity_id: light.kitchen_2
  domain: light
- condition: time
  before: 06:00:00
  after: 05:00:00
  weekday:
  - mon
  - tue
  - wed
  - thu
  - fri
  - sat
  - sun
action:
- service: hue.hue_activate_scene
  data:
    scene_name: Relax
    group_name: Kitchen
mode: single