---

id: '1650605849825'
alias: Laundry - Turn off dim lights at night after motion ends
description: ''
trigger:
- type: no_motion
  platform: device
  device_id: adf55e9c67a1d24e1381a322bd5cb035
  entity_id: binary_sensor.lumi_lumi_sensor_motion_ias_zone
  domain: binary_sensor
condition:
  - condition: state
    entity_id: schedule.nightlight_hours
    state: "on"
  - condition: device
    type: is_on
    device_id: dd9925129896c0ef1b24d2c784344190
    entity_id: light.laundry
    domain: light
action:
- type: turn_off
  device_id: dd9925129896c0ef1b24d2c784344190
  entity_id: light.laundry
  domain: light
  metadata:
    secondary: false
mode: single