---

id: '5494eab3-4c73-4652-80c5-9cff7535da02'
alias: Office - turns on lights with motion during the day
description: ''
trigger:
  - type: motion
    platform: device
    device_id: acf9c03923cd0d73d6761d52457b23b8
    entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_iaszone
    domain: binary_sensor
condition:
  - condition: and
    conditions: 
      - condition: state
        entity_id: schedule.workday_schedule
        state: "on"
      - condition: state
        entity_id: light.office_2
        state: "off"
action:
  - service: hue.hue_activate_scene
    data:
      scene_name: Sunday Morning
      group_name: Office
mode: single