---

id: 'b64f463d-43da-4424-87bb-1a48283b1a76'
alias: Office - turns on lights with motion outside of business hours
description: ''
trigger:
  - type: motion
    platform: device
    device_id: acf9c03923cd0d73d6761d52457b23b8
    entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_iaszone
    domain: binary_sensor
condition:
  - condition: and
    conditions: 
      - condition: state
        entity_id: schedule.workday_schedule
        state: "off"
      - condition: state
        entity_id: light.office_2
        state: "off"
action:
  - service: hue.hue_activate_scene
    data:
      scene_name: Bright
      group_name: Office
mode: single