---

id: 'df408ab3-f098-4789-92d7-457244daec64'
alias: Office - Turn off the office lights after motion ends
description: ''
trigger:
  - type: not_occupied
    platform: device
    device_id: acf9c03923cd0d73d6761d52457b23b8
    entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_occupancy
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 30
condition:
action:
  - type: turn_off
    device_id: 8e349ab99356fdc1cc6538e81d5cae21
    entity_id: light.office
    domain: light
mode: single