---

id: '1641099129998'
alias: Notification - Front door low battery
description: Sends a notification when the front door Yale Assure SL lock has low
  charge remaining.
trigger:
- type: battery_level
  platform: device
  device_id: 7e4bb806c485d30f69129236ba75303a
  entity_id: sensor.front_door_lock_8cfff910_power
  domain: sensor
  below: 25
condition: []
action:
- service: notify.notify
  data:
    message: Front door has low battery
    title: Front door has low battery
mode: single