---
#
# Turns off the workshop lights when motion ends
# @author Michael Greenhill
# @updated 2022-07-12
#

id: '17edd95c-afe9-4754-b4cb-749b4e75726b'
alias: Workshop - Turn off the lights with motion
description: 'Turns off the workshop lights after motion ends'

trigger:
- type: no_motion
  platform: device
  device_id: 2a9a65b91131d7ec0087ea2570483c01
  entity_id: binary_sensor.lumi_lumi_sensor_motion_dbcc2205_ias_zone
  domain: binary_sensor

action:
- type: turn_off
  device_id: 689fce540b49acf87e37794fc7d0ae91
  entity_id: switch.workshop_lights
  domain: switch

mode: single