---
#
# Turns on the workshop lights when motion is detected
# @author Michael Greenhill
# @updated 2022-07-12
#

id: '56a0b984-3bce-4c0c-9fbf-7cd7cbfe0d80'
alias: Workshop - Turn on the lights with motion
description: 'Turns on the workshop lights when motion is detected'

trigger:
- type: motion
  platform: device
  device_id: 2a9a65b91131d7ec0087ea2570483c01
  entity_id: binary_sensor.lumi_lumi_sensor_motion_dbcc2205_ias_zone
  domain: binary_sensor

action:
- type: turn_on
  device_id: 689fce540b49acf87e37794fc7d0ae91
  entity_id: switch.workshop_lights
  domain: switch

mode: single