---
#
# Uses the occupancy sensor on the Aqara zigbee motion sensors to throw an alarm if occupancy is detected while we are not home.
# @author Michael Greenhill
# @updated 2022-06-28
#

id: '1650606704037'
alias: Alarm - Workshop occupancy while away
description: 'Uses the occupancy sensor on the Aqara zigbee motion sensors to throw an alarm if occupancy is detected while we are not home.'

trigger:
  - type: occupied
    platform: device
    device_id: 2a9a65b91131d7ec0087ea2570483c01
    entity_id: binary_sensor.lumi_lumi_sensor_motion_dbcc2205_occupancy
    domain: binary_sensor

condition:
  - condition: not
    conditions:
    - condition: state
      entity_id: group.people
      for:
        hours: 0
        minutes: 0
        seconds: 0
      state: home

action:
  - service: notify.amazon_ses
    data:
      message: ALARM - Indoor occupancy detected
      title: ALARM - Indoor occupancy detected
      target: doctorjbeam@gmail.com
  - service: notify.mobile_app_pixel_5
    data:
      message: ALARM - Indoor occupancy detected
      title: ALARM - Indoor occupancy detected

mode: single
