---

id: "756fe931-2813-4954-a3ef-f93b4818b4a2"
alias: Turn on the inside lights with motion when it's dark
description: ""
trigger:
  - type: motion
    platform: device
    device_id: 41622ebcffbf84a3fb68b12e38e010cf
    entity_id: binary_sensor.lumi_lumi_sensor_motion_7b9b4305_ias_zone
    domain: binary_sensor
condition:
  - condition: and
    conditions:
      - condition: device
        type: is_off
        device_id: 56eb305fe63b59717055d2281df37139
        entity_id: light.living_room_downlight_6
        domain: light
      - condition: numeric_state
        entity_id: sensor.backyard_anemometer_lux
        below: 200
      - condition: state
        entity_id: schedule.nightlight_hours
        state: "off"
action:
  - service: hue.hue_activate_scene
    data:
      group_name: Lounge
      scene_name: Bright
  - service: hue.hue_activate_scene
    data:
      group_name: Kitchen
      scene_name: Bright
mode: single
