---

id: '1614987008873'
alias: Living Room - Sound System - ON
description: 'Automatically turns on the sound system when the TV is turned on.'
trigger:
- platform: state
  entity_id: switch.living_room_tv
  from: 'off'
  to: 'on'
condition: []
action:
- type: turn_on
  device_id: 855e34d2e92c4228b9f5f6f01dc0e485
  entity_id: switch.shed
  domain: switch
mode: single